### ISSUE TITLE
Contact form

### ISSUE THREAD

**Issue by ShMuhammad** [fac31/mohammed-dexter-agency-website#3]
Create a form to allow customers to get in touch if they are interested in working with our agency.

**Comment by DexterHill0** [comment]
I like the look of the contact form so far! I would say there is one interesting thing you could add maybe.
With the forms inputs, you can set them to `required` as well as providing a pattern form them. A cool css feature about inputs is you can check if the input is valid with `:valid` so that means we could have the red square turn green if the input is valid, without needing to have pressed the submit button.
If you add an extra class to the `square` div for each input, like `<div class="square name-square"></div>` for the name input, and then in the css add:
```css
.name-square:has(~ #nameField:valid) {
    background-color: var(--ok-button-color); 
}
```
the square will turn green when the input is valid. The `has` selector is basically only applying the style to `name-square` if the input at the same level (`~`) is valid.
